#! python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 18 10:46:43 2023

@author: kronq
"""

######################################################
## Column headers and defaults for the USDA databases
## usda_data.csv & usda_dataC.csv 
######################################################

col_heads = [
 'Shrt_Desc',
 'Water_(g)',
 'Energ_Kcal',
 'Protein_(g)',
 'Lipid_Tot_(g)',
 'Ash_(g)',
 'Carbohydrt_(g)',
 'Fiber_TD_(g)',
 'Sugar_Tot_(g)',
 'Calcium_(mg)',
 'Iron_(mg)',
 'Magnesium_(mg)',
 'Phosphorus_(mg)',
 'Potassium_(mg)',
 'Sodium_(mg)',
 'Zinc_(mg)',
 'Copper_mg)',
 'Manganese_(mg)',
 'Selenium_(µg)',
 'Vit_C_(mg)',
 'Thiamin_(mg)',
 'Riboflavin_(mg)',
 'Niacin_(mg)',
 'Panto_Acid_mg)',
 'Vit_B6_(mg)',
 'Folate_Tot_(µg)',
 'Folic_Acid_(µg)',
 'Food_Folate_(µg)',
 'Folate_DFE_(µg)',
 'Choline_Tot_(mg)',
 'Vit_B12_(µg)',
 'Vit_A_IU',
 'Vit_A_RAE',
 'Retinol_(µg)',
 'Alpha_Carot_(µg)',
 'Beta_Carot_(µg)',
 'Beta_Crypt_(µg)',
 'Lycopene_(µg)',
 'Lut+Zea_(µg)',
 'Vit_E_(mg)',
 'Vit_D_µg',
 'Vit_D_IU',
 'Vit_K_(µg)',
 'FA_Sat_(g)',
 'FA_Mono_(g)',
 'FA_Poly_(g)',
 'Cholestrl_(mg)',
 'GmWt_1',
 'GmWt_Desc1',
 'GmWt_2',
 'GmWt_Desc2',
 'Refuse_Pct'
 ]

# # default_fields = [4,5,6,7,8,9,10,49,50]
# default_fields = [
# 'Energ_Kcal',
# 'Protein_(g)',
# 'Carbohydrt_(g)',
# 'Fiber_TD_(g)',
# 'Sugar_Tot_(g)',
# 'Lipid_Tot_(g)',
# 'FA_Sat_(g)',
# 'FA_Mono_(g)',
# 'FA_Poly_(g)',
# 'Water_(g)',
# 'GmWt_1',
# 'GmWt_Desc1'
# ]

default_fields = ['Energ_Kcal', 
                  'Lipid_Tot_(g)', 
                  'FA_Sat_(g)', 
                  'Cholestrl_(mg)', 
                  'Carbohydrt_(g)', 
                  'Sugar_Tot_(g)',
                  'Fiber_TD_(g)', 
                  'Protein_(g)', 
                  'Vit_A_RAE',
                  'Vit_C_(mg)', 
                  'Thiamin_(mg)', 
                  'Niacin_(mg)', 
                  'Sodium_(mg)', 
                  'Potassium_(mg)', 
                  'Phosphorus_(mg)', 
                  'Iron_(mg)',
                  'Calcium_(mg)',
                  'GmWt_1',
                  'GmWt_Desc1']

col_dict = {
 # 1: 'NDB_No',
 2: 'Shrt_Desc',
 3: 'Water_(g)',
 4: 'Energ_Kcal',
 5: 'Protein_(g)',
 6: 'Lipid_Tot_(g)',
 7: 'Ash_(g)',
 8: 'Carbohydrt_(g)',
 9: 'Fiber_TD_(g)',
 10: 'Sugar_Tot_(g)',
 11: 'Calcium_(mg)',
 12: 'Iron_(mg)',
 13: 'Magnesium_(mg)',
 14: 'Phosphorus_(mg)',
 15: 'Potassium_(mg)',
 16: 'Sodium_(mg)',
 17: 'Zinc_(mg)',
 18: 'Copper_mg)',
 19: 'Manganese_(mg)',
 20: 'Selenium_(µg)',
 21: 'Vit_C_(mg)',
 22: 'Thiamin_(mg)',
 23: 'Riboflavin_(mg)',
 24: 'Niacin_(mg)',
 25: 'Panto_Acid_mg)',
 26: 'Vit_B6_(mg)',
 27: 'Folate_Tot_(µg)',
 28: 'Folic_Acid_(µg)',
 29: 'Food_Folate_(µg)',
 30: 'Folate_DFE_(µg)',
 31: 'Choline_Tot_(mg)',
 32: 'Vit_B12_(µg)',
 33: 'Vit_A_IU',
 34: 'Vit_A_RAE',
 35: 'Retinol_(µg)',
 36: 'Alpha_Carot_(µg)',
 37: 'Beta_Carot_(µg)',
 38: 'Beta_Crypt_(µg)',
 39: 'Lycopene_(µg)',
 40: 'Lut+Zea_(µg)',
 41: 'Vit_E_(mg)',
 42: 'Vit_D_µg',
 43: 'Vit_D_IU',
 44: 'Vit_K_(µg)',
 45: 'FA_Sat_(g)',
 46: 'FA_Mono_(g)',
 47: 'FA_Poly_(g)',
 48: 'Cholestrl_(mg)',
 49: 'GmWt_1',
 50: 'GmWt_Desc1',
 51: 'GmWt_2',
 52: 'GmWt_Desc2',
 53: 'Refuse_Pct'}

##############################################
# Column headers and defaults for
# MyDataFood.csv database
##############################################

default_heads = [
 # 'name',
 # 'Food Group',
 'Calories',
 'Fat (g)',
 'Saturated Fats (g)',
 'Cholesterol (mg)',
 'Carbohydrate (g)',
 'Sugars (g)',
 'Fiber (g)',
 'Protein (g)',
 'Vitamin A, RAE (mcg)',
 'Vitamin C (mg)',
 'Thiamin (B1) (mg)',
 'Niacin (B3) (mg)',
 'Sodium (mg)',
 'Potassium, K (mg)',
 'Phosphorus, P (mg)',
 'Iron, Fe (mg)',
 'Calcium (mg)',
 'Serving Weight 1 (g)',
 'Serving Description 1 (g)'
]

heads = [
 'ID',
 'name',
 'Food Group',
 'Calories',
 'Fat (g)',
 'Protein (g)',
 'Carbohydrate (g)',
 'Sugars (g)',
 'Fiber (g)',
 'Cholesterol (mg)',
 'Saturated Fats (g)',
 'Calcium (mg)',
 'Iron, Fe (mg)',
 'Potassium, K (mg)',
 'Magnesium (mg)',
 'Vitamin A, IU (IU)',
 'Vitamin A, RAE (mcg)',
 'Vitamin C (mg)',
 'Vitamin B-12 (mcg)',
 'Vitamin D (mcg)',
 'Vitamin E (Alpha-Tocopherol) (mg)',
 'Added Sugar (g)',
 'Net-Carbs (g)',
 'Water (g)',
 'Omega 3s (mg)',
 'Omega 6s (mg)',
 'PRAL score',
 'Trans Fatty Acids (g)',
 'Soluble Fiber (g)',
 'Insoluble Fiber (g)',
 'Sucrose (g)',
 'Glucose (Dextrose) (g)',
 'Fructose (g)',
 'Lactose (g)',
 'Maltose (g)',
 'Galactose (g)',
 'Starch (g)',
 'Total sugar alcohols (g)',
 'Phosphorus, P (mg)',
 'Sodium (mg)',
 'Zinc, Zn (mg)',
 'Copper, Cu (mg)',
 'Manganese (mg)',
 'Selenium, Se (mcg)',
 'Fluoride, F (mcg)',
 'Molybdenum (mcg)',
 'Chlorine (mg)',
 'Thiamin (B1) (mg)',
 'Riboflavin (B2) (mg)',
 'Niacin (B3) (mg)',
 'Pantothenic acid (B5) (mg)',
 'Vitamin B6 (mg)',
 'Biotin (B7) (mcg)',
 'Folate (B9) (mcg)',
 'Folic acid (mcg)',
 'Food Folate (mcg)',
 'Folate DFE (mcg)',
 'Choline (mg)',
 'Betaine (mg)',
 'Retinol (mcg)',
 'Carotene, beta (mcg)',
 'Carotene, alpha (mcg)',
 'Lycopene (mcg)',
 'Lutein + Zeaxanthin (mcg)',
 'Vitamin D2 (ergocalciferol) (mcg)',
 'Vitamin D3 (cholecalciferol) (mcg)',
 'Vitamin D (IU) (IU)',
 'Vitamin K (mcg)',
 'Dihydrophylloquinone (mcg)',
 'Menaquinone-4 (mcg)',
 'Fatty acids, total monounsaturated (mg)',
 'Fatty acids, total polyunsaturated (mg)',
 '18:3 n-3 c,c,c (ALA) (mg)',
 '20:5 n-3 (EPA) (mg)',
 '22:5 n-3 (DPA) (mg)',
 '22:6 n-3 (DHA) (mg)',
 'Tryptophan (mg)',
 'Threonine (mg)',
 'Isoleucine (mg)',
 'Leucine (mg)',
 'Lysine (mg)',
 'Methionine (mg)',
 'Cystine (mg)',
 'Phenylalanine (mg)',
 'Tyrosine (mg)',
 'Valine (mg)',
 'Arginine (mg)',
 'Histidine (mg)',
 'Alanine (mg)',
 'Aspartic acid (mg)',
 'Glutamic acid (mg)',
 'Glycine (mg)',
 'Proline (mg)',
 'Serine (mg)',
 'Hydroxyproline (mg)',
 'Alcohol (g)',
 'Caffeine (mg)',
 'Theobromine (mg)',
 'Serving Weight 1 (g)',
 'Serving Description 1 (g)',
 'Serving Weight 2 (g)',
 'Serving Description 2 (g)',
 'Serving Weight 3 (g)',
 'Serving Description 3 (g)',
 'Serving Weight 4 (g)',
 'Serving Description 4 (g)',
 'Serving Weight 5 (g)',
 'Serving Description 5 (g)',
 'Serving Weight 6 (g)',
 'Serving Description 6 (g)',
 'Serving Weight 7 (g)',
 'Serving Description 7 (g)',
 'Serving Weight 8 (g)',
 'Serving Description 8 (g)',
 'Serving Weight 9 (g)',
 'Serving Description 9 (g)',
 '200 Calorie Weight (g)']

heads_dict = {
 1: 'ID',
 2: 'name',
 3: 'Food Group',
 4: 'Calories',
 5: 'Fat (g)',
 6: 'Protein (g)',
 7: 'Carbohydrate (g)',
 8: 'Sugars (g)',
 9: 'Fiber (g)',
 10: 'Cholesterol (mg)',
 11: 'Saturated Fats (g)',
 12: 'Calcium (mg)',
 13: 'Iron, Fe (mg)',
 14: 'Potassium, K (mg)',
 15: 'Magnesium (mg)',
 16: 'Vitamin A, IU (IU)',
 17: 'Vitamin A, RAE (mcg)',
 18: 'Vitamin C (mg)',
 19: 'Vitamin B-12 (mcg)',
 20: 'Vitamin D (mcg)',
 21: 'Vitamin E (Alpha-Tocopherol) (mg)',
 22: 'Added Sugar (g)',
 23: 'Net-Carbs (g)',
 24: 'Water (g)',
 25: 'Omega 3s (mg)',
 26: 'Omega 6s (mg)',
 27: 'PRAL score',
 28: 'Trans Fatty Acids (g)',
 29: 'Soluble Fiber (g)',
 30: 'Insoluble Fiber (g)',
 31: 'Sucrose (g)',
 32: 'Glucose (Dextrose) (g)',
 33: 'Fructose (g)',
 34: 'Lactose (g)',
 35: 'Maltose (g)',
 36: 'Galactose (g)',
 37: 'Starch (g)',
 38: 'Total sugar alcohols (g)',
 39: 'Phosphorus, P (mg)',
 40: 'Sodium (mg)',
 41: 'Zinc, Zn (mg)',
 42: 'Copper, Cu (mg)',
 43: 'Manganese (mg)',
 44: 'Selenium, Se (mcg)',
 45: 'Fluoride, F (mcg)',
 46: 'Molybdenum (mcg)',
 47: 'Chlorine (mg)',
 48: 'Thiamin (B1) (mg)',
 49: 'Riboflavin (B2) (mg)',
 50: 'Niacin (B3) (mg)',
 51: 'Pantothenic acid (B5) (mg)',
 52: 'Vitamin B6 (mg)',
 53: 'Biotin (B7) (mcg)',
 54: 'Folate (B9) (mcg)',
 55: 'Folic acid (mcg)',
 56: 'Food Folate (mcg)',
 57: 'Folate DFE (mcg)',
 58: 'Choline (mg)',
 59: 'Betaine (mg)',
 60: 'Retinol (mcg)',
 61: 'Carotene, beta (mcg)',
 62: 'Carotene, alpha (mcg)',
 63: 'Lycopene (mcg)',
 64: 'Lutein + Zeaxanthin (mcg)',
 65: 'Vitamin D2 (ergocalciferol) (mcg)',
 66: 'Vitamin D3 (cholecalciferol) (mcg)',
 67: 'Vitamin D (IU) (IU)',
 68: 'Vitamin K (mcg)',
 69: 'Dihydrophylloquinone (mcg)',
 70: 'Menaquinone-4 (mcg)',
 71: 'Fatty acids, total monounsaturated (mg)',
 72: 'Fatty acids, total polyunsaturated (mg)',
 73: '18:3 n-3 c,c,c (ALA) (mg)',
 74: '20:5 n-3 (EPA) (mg)',
 75: '22:5 n-3 (DPA) (mg)',
 76: '22:6 n-3 (DHA) (mg)',
 77: 'Tryptophan (mg)',
 78: 'Threonine (mg)',
 79: 'Isoleucine (mg)',
 80: 'Leucine (mg)',
 81: 'Lysine (mg)',
 82: 'Methionine (mg)',
 83: 'Cystine (mg)',
 84: 'Phenylalanine (mg)',
 85: 'Tyrosine (mg)',
 86: 'Valine (mg)',
 87: 'Arginine (mg)',
 88: 'Histidine (mg)',
 89: 'Alanine (mg)',
 90: 'Aspartic acid (mg)',
 91: 'Glutamic acid (mg)',
 92: 'Glycine (mg)',
 93: 'Proline (mg)',
 94: 'Serine (mg)',
 95: 'Hydroxyproline (mg)',
 96: 'Alcohol (g)',
 97: 'Caffeine (mg)',
 98: 'Theobromine (mg)',
 99: 'Serving Weight 1 (g)',
 100: 'Serving Description 1 (g)',
 101: 'Serving Weight 2 (g)',
 102: 'Serving Description 2 (g)',
 103: 'Serving Weight 3 (g)',
 104: 'Serving Description 3 (g)',
 105: 'Serving Weight 4 (g)',
 106: 'Serving Description 4 (g)',
 107: 'Serving Weight 5 (g)',
 108: 'Serving Description 5 (g)',
 109: 'Serving Weight 6 (g)',
 110: 'Serving Description 6 (g)',
 111: 'Serving Weight 7 (g)',
 112: 'Serving Description 7 (g)',
 113: 'Serving Weight 8 (g)',
 114: 'Serving Description 8 (g)',
 115: 'Serving Weight 9 (g)',
 116: 'Serving Description 9 (g)',
 117: '200 Calorie Weight (g)'}